version: "2"

plugins:
  eslint:
    enabled: true

checks:
  method-complexity:
    enabled: false
  method-lines:
    config:
      threshold: 150

ratings:
   paths:
    - "**.js"
    - "**.jsx"
    - "**.css"
    - "**.less"
    - "**.scss"
    - "**.sss"

exclude_paths:
- static/**/*
- src/templates/b16-tomorrow-dark.css
